// Expo config plugin for the Ibadah Lock AccessibilityService (Android only).
// Registered in app.json as "./modules/ibadah-lock/plugin".
//
// It adds to the generated Android project:
//   - the <service> declaration, protected by BIND_ACCESSIBILITY_SERVICE so only the system can bind it
//   - res/xml/ibadah_lock_accessibility_service.xml (the service's configuration)
//   - the user-facing label and description strings shown in Settings → Accessibility
// iOS is untouched: no FamilyControls entitlement is added (see ../README.md).
const fs = require('fs');
const path = require('path');
const { AndroidConfig, withAndroidManifest, withDangerousMod, withStringsXml } = require('expo/config-plugins');

const SERVICE_CLASS = 'expo.modules.ibadahlock.IbadahLockAccessibilityService';
const XML_NAME = 'ibadah_lock_accessibility_service';

const DEFAULT_LABEL = 'Ibtida Ibadah Lock';
const DEFAULT_DESCRIPTION =
  'Ibadah Lock keeps the apps you choose closed while a lock session you started is running. ' +
  'During a session, this service only checks which app has just opened. If it is one you chose to lock ' +
  '(for example Instagram or YouTube), Ibtida brings you back to your dhikr. ' +
  'It does not read what is on your screen, does not see what you type, and does not collect or send any data. ' +
  'Outside a session it does nothing. Phone, emergency and SMS apps are never locked. ' +
  'You can turn this off here at any time, and end a session early with the emergency unlock in Ibtida.';

// No static android:packageNames: on connect, the service narrows delivery at runtime to the apps
// in the active session, and to Ibtida's own package when no session is running.
const SERVICE_XML = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by modules/ibadah-lock/plugin. Only window-state changes; window content is never retrieved. -->
<accessibility-service xmlns:android="http://schemas.android.com/apk/res/android"
    android:accessibilityEventTypes="typeWindowStateChanged"
    android:accessibilityFeedbackType="feedbackGeneric"
    android:accessibilityFlags="flagDefault"
    android:canRetrieveWindowContent="false"
    android:notificationTimeout="100"
    android:isAccessibilityTool="false"
    android:description="@string/ibadah_lock_accessibility_description"
    android:summary="@string/ibadah_lock_accessibility_summary" />
`;

function withLockService(config) {
  return withAndroidManifest(config, cfg => {
    const app = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults);
    app.service = (app.service || []).filter(s => s.$['android:name'] !== SERVICE_CLASS);
    app.service.push({
      $: {
        'android:name': SERVICE_CLASS,
        'android:label': '@string/ibadah_lock_accessibility_label',
        'android:permission': 'android.permission.BIND_ACCESSIBILITY_SERVICE',
        'android:exported': 'false',
      },
      'intent-filter': [{ action: [{ $: { 'android:name': 'android.accessibilityservice.AccessibilityService' } }] }],
      'meta-data': [{ $: { 'android:name': 'android.accessibilityservice', 'android:resource': `@xml/${XML_NAME}` } }],
    });
    return cfg;
  });
}

function withLockStrings(config, { label, description }) {
  return withStringsXml(config, cfg => {
    const items = [
      AndroidConfig.Resources.buildResourceItem({ name: 'ibadah_lock_accessibility_label', value: label }),
      AndroidConfig.Resources.buildResourceItem({ name: 'ibadah_lock_accessibility_summary', value: 'Returns you to Ibtida when a locked app opens during Ibadah Lock.' }),
      AndroidConfig.Resources.buildResourceItem({ name: 'ibadah_lock_accessibility_description', value: description }),
    ];
    cfg.modResults = AndroidConfig.Strings.setStringItem(items, cfg.modResults);
    return cfg;
  });
}

function withLockServiceXml(config) {
  return withDangerousMod(config, [
    'android',
    async cfg => {
      const dir = path.join(cfg.modRequest.platformProjectRoot, 'app', 'src', 'main', 'res', 'xml');
      await fs.promises.mkdir(dir, { recursive: true });
      await fs.promises.writeFile(path.join(dir, `${XML_NAME}.xml`), SERVICE_XML);
      return cfg;
    },
  ]);
}

module.exports = function withIbadahLock(config, props = {}) {
  const opts = {
    label: props.label || DEFAULT_LABEL,
    description: props.description || DEFAULT_DESCRIPTION,
  };
  config = withLockService(config);
  config = withLockStrings(config, opts);
  config = withLockServiceXml(config);
  return config;
};
